title: NodeSlicer Configuration Schema
type: object
properties:
  save:
    description: Save configuration to the specified file
    type: string

  load:
    description: >
      Load configuration from the specified file.
      It can be used more than once to load options from multiple files.
    type: string

  outputFile:
    description: File to output G-code to
    type: string

  outputDirectory:
    description: Directory to output G-code-files to
    type: string

  inputFiles:
    description: Input STL-files
    type: array
    items:
      type: string

  # Non-slicing actions (no G-code will be generated):
  repair:
    description: Repair given STL files and save them as <name>_fixed.obj
    type: boolean

  cut:
    description: >
      Cut given input files at given Z (relative) and
      export them as <name>_upper.stl and <name>_lower.stl
    type: number

  info:
    description: Output information about the supplied file(s)
    type: boolean

  threads:
    description: Number of threads to use
    type: number
    default: 2
    minimum: 1

   # Output options:
   postProcess:
    description: >
      Generated G-code will be processed with the supplied script.
      Call this more than once to process through multiple scripts.
     type: boolean

  exportSvg:
    description: Export a SVG file containing slices instead of G-code.
    type: boolean

  merge:
    description: >
      If multiple files are supplied, they will be composed into a single
      print rather than processed individually.
    type: boolean

  # Printer Options
  nozzleDiameter:
   description:  Diameter of nozzle in mm
   type: number
   default: 0.5

  printCenter:
    description: Coordinates in mm of the point to center the print around
    type: object
    properties:
      x:
        type: number
      y:
        type: number
    default:
      x: 100
      y: 100

  zOffset:
   description: Additional height in mm to add to vertical coordinates
   type: number
   default: 0

  gCodeFlavor:
    description: The type of G-code to generate
    default: reprap
    enum:
      - reprap
      - teacup
      - makerware
      - sailfish
      - mach3
      - no-extrusion

  useRelativeEDistances:
    description: Enable this to get relative E values
    type: boolean
    default: false

  useFirmwareRetraction:
    description: Enable firmware-controlled retraction using G10/G11
    type: boolean
    default: false

  gCodeArcs:
    description: >
      Use G2/G3 commands for native arcs
      (experimental, not supported by all firmwares)
    type: boolean
    default: false

  g0:
    description: >
      Use G0 commands for retraction
      (experimental, not supported by all firmwares)
    type: boolean
    default: false

  gCodeComments:
    description: Make G-code verbose by adding comments
    type: boolean
    default: false

  vibrationLimit:
    description: >
      Limit the frequency of moves on x- and y-axes in Hz
      (set zero to disable)
    default: 0
